version: "3"
services:
  agent:
    image:  gcr.io/print-cloud-software/moloon:1.0.0
    container_name: agent
    # environment:
    #   - NO_PROXY
    #   - HTTP_PROXY
    #   - HTTPS_PROXY
    #   - no_proxy
    #   - http_proxy
    #   - https_proxy
    ports:
      - "3001:3000" # http
    entrypoint:
      - /go/bin/moloon
      - server
  controller:
      image:  gcr.io/print-cloud-software/moloon:1.0.0
      container_name: controller
      environment:
        # - NO_PROXY
        # - HTTP_PROXY
        # - HTTPS_PROXY
        # - no_proxy
        # - http_proxy
        # - https_proxy
        - DISCOVERY_CONFIG=file
        - DISCOVERY_AGENTS=`http://agent:3000/`
      ports:
        - "3002:3000" # http
      entrypoint:
        - /go/bin/moloon
        - controller
      links:
          - agent